SystemOrganization addCategory: #'OmniBrowser2-Announcements'!
SystemOrganization addCategory: #'OmniBrowser2-Commands'!
SystemOrganization addCategory: #'OmniBrowser2-Filters'!
SystemOrganization addCategory: #'OmniBrowser2-Kernel'!
SystemOrganization addCategory: #'OmniBrowser2-Nodes'!
SystemOrganization addCategory: #'OmniBrowser2-Notifications'!
SystemOrganization addCategory: #'OmniBrowser2-Panels'!
SystemOrganization addCategory: #'OmniBrowser2-Utilities'!
