SystemOrganization addCategory: #'O2-Refactory-Browsers'!
SystemOrganization addCategory: #'O2-Refactory-Changes'!
SystemOrganization addCategory: #'O2-Refactory-Commands'!
SystemOrganization addCategory: #'O2-Refactory-Lint'!
SystemOrganization addCategory: #'O2-Refactory-Matcher'!
SystemOrganization addCategory: #'O2-Refactory-Refactoring'!
SystemOrganization addCategory: #'O2-Refactory-Tools'!
