SystemOrganization addCategory: #'O2-Standard-Announcements'!
SystemOrganization addCategory: #'O2-Standard-Browsers'!
SystemOrganization addCategory: #'O2-Standard-Commands'!
SystemOrganization addCategory: #'O2-Standard-Definitions'!
SystemOrganization addCategory: #'O2-Standard-Filters'!
SystemOrganization addCategory: #'O2-Standard-Nodes'!
SystemOrganization addCategory: #'O2-Standard-Panels'!
SystemOrganization addCategory: #'O2-Standard-Utilities'!
